import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NourishNet - Food With a Smile',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
